title:              Just Think
email:              huseyinlinicat144@gmail.com
description:        Qüvvət elmdədir, başqa cür heç kəs, heç kəsə üstünlük eyləyə bilməz. 
author:             Just Think
baseurl:            /startbootstrap-clean-blog-jekyll/
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:  
github_username:   
facebook_username:  Just Think
instagram_username:  Just Think  
linkedin_username:  Just Think

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           100
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
